# mouse sens in sddm
Section	"InputClass"
	Identifier "Mouse Acceleration"
	MatchIsPointer "on"
	MatchIsTouchpad "off"
	Driver "libinput"
	Option "AccelProfile" "flat"
EndSection


# touchpad sens in sddm
Section	"InputClass"
	Identifier "Touchpad Acceleration"
	MatchIsTouchpad "on"
	Driver "libinput"
	Option "AccelProfile" "adaptive"
	Option "AccelSpeed" "0"
EndSection


# touchpad tap function
Section "InputClass"
	Identifier "touchpad"
	MatchIsTouchpad "on"
	Option "Tapping" "on"
	Option "NaturalScrolling" "true"
EndSection
