# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C8D7E3
background         #121019
cursor             #6A7BA4

active_tab_foreground     #121019
active_tab_background     #C8D7E3
inactive_tab_foreground   #C8D7E3
inactive_tab_background   #121019

active_border_color   #C8D7E3
inactive_border_color #121019
bell_border_color     #040A27

color0      #393941
color1		#040A27
color2		#08164C
color3		#0C1C4F
color4		#13268D
color5		#324B6F
color6		#4A6B84
color7		#A8BECF
color8		#768591
color9		#060D34
color10		#0B1E65
color11		#11256A
color12		#1933BC
color13		#426494
color14		#638EB0
color15		#A8BECF
